# Generated by Django 2.1.3 on 2018-11-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'Aliases'},
        ),
    ]
