# Generated by Django 2.1.3 on 2018-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0002_auto_20181126_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
